// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9j7tXScd9ZdZdx8I1ZLvZzO_4TnNkD7M',
    appId: '1:736707957691:web:587939e797348e994c2a9e',
    messagingSenderId: '736707957691',
    projectId: 'flutterfirebase-e7462',
    authDomain: 'flutterfirebase-e7462.firebaseapp.com',
    storageBucket: 'flutterfirebase-e7462.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPrw_SHdrYj8Hai9sI9HOBGKWEqT2KY5Q',
    appId: '1:736707957691:android:c612e78c590f8c054c2a9e',
    messagingSenderId: '736707957691',
    projectId: 'flutterfirebase-e7462',
    storageBucket: 'flutterfirebase-e7462.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCKwRjsn4g6G7bYpKFM0Rfr-OWUbwdq2k',
    appId: '1:736707957691:ios:5dbf9af6b8360b174c2a9e',
    messagingSenderId: '736707957691',
    projectId: 'flutterfirebase-e7462',
    storageBucket: 'flutterfirebase-e7462.appspot.com',
    iosBundleId: 'com.example.flutterFirebase2324',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCKwRjsn4g6G7bYpKFM0Rfr-OWUbwdq2k',
    appId: '1:736707957691:ios:91d255c57580e89b4c2a9e',
    messagingSenderId: '736707957691',
    projectId: 'flutterfirebase-e7462',
    storageBucket: 'flutterfirebase-e7462.appspot.com',
    iosBundleId: 'com.example.flutterFirebase2324.RunnerTests',
  );
}
